
//CREATE USER
POST http://localhost:3001/users
Content-Type: application/json

{
    "fullName": "tis",
    "email": "daru@gmail.com",
    "password": "123321",
    "phone": "12332145",
    "confPassword": "123321",
    "accountType": "admin"
}

###
//FIND ALL USERS
GET http://localhost:3001/users
Content-Type: application/json

###
//FIND SPECIFIC USER
GET http://localhost:3001/users/5
Content-Type: application/json

###
//UPDATE USER
PATCH  http://localhost:3001/users/2
Content-Type: application/json

{
    "fullName": "daradr",
    "email": "Nh212aZulIshutin@gmail.com",
    "password": "321321",
    "phone": "12332145",
    "confPassword": "321321",
    "accountType": "customer"
}

###
//DESTROY!!!
DELETE http://localhost:3001/users/4

###
//LOGIN USER

POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "daru@gmail.com",
    "password": "123321"
}

###
//ME
GET http://localhost:3001/me


###
//LOGOUT
DELETE http://localhost:3001/logout