
//CREATE USER
POST http://localhost:3001/users
Content-Type: application/json

{
    "fullName": "daradr",
    "email": "Nh212aZulIshutin@gmail.com",
    "password": "123321",
    "phone": "12332145",
    "confPassword": "123321",
    "accountType": "customer"
}

###
//FIND ALL USERS
GET http://localhost:3001/users
Content-Type: application/json